services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: novellib
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./uploads:/app/uploads
