services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.livedev
    container_name: novellib
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
