FROM node:lts-slim AS base

# Build stage
FROM base AS build

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

# Run Sequelize migrations and seed the database
RUN npm run migrate && \
    npm run seed

# Runtime Stage
FROM base AS runtime

RUN addgroup --system --gid 1001 nextjs
RUN adduser --system --uid 1001 nextjs

USER nextjs

WORKDIR /app

COPY --from=build /app/public ./public

RUN mkdir .next

COPY --from=build --chown=nextjs /app/.next/standalone .
COPY --from=build --chown=nextjs /app/.next/static ./.next/static

ENV NODE_ENV=production

# Expose the port Next.js app will run on
EXPOSE 3000

CMD [ "node","server.js" ]