services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: novellib
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./public:/home/nextjs/app/public
      - ./uploads:/home/nextjs/app/uploads
      # - ./logs:/home/nextjs/app/logs
