services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prd
    container_name: novellib_ui
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - ./.env.production
