services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prd
    container_name: novellib_api
    restart: unless-stopped
    ports:
      - "5173:3000"
    env_file:
      - ./.env.prd
    volumes:
      - ./public:/home/node/app/public
