services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: novellib_api
    ports:
      - "3080:3080"
    env_file:
      - ./.env.dev
    volumes:
      - ./public:/home/node/app/public
      - ./logs:/home/node/app/logs