version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: novellib_api
    ports:
      - "5173:3000"
    env_file:
      - ./.env.dev
    volumes:
      - .:/app
      - /app/node_modules
