FROM node:lts-slim AS base

# build stage
FROM base  AS build

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build:prd

# runtime stage
FROM base AS final

RUN mkdir -p /home/node/app/dist && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json .

# install only production dependencies
RUN npm install --only=production

COPY --chown=node:node --from=build /app/dist ./dist

USER node

EXPOSE 3000

ENTRYPOINT [ "node", "./dist/main.js" ]